### ISSUE TITLE
[Enhancement] API request enhancement

### ISSUE THREAD

**Issue by Soneoylys** [tylearymf/UniGPT#1]
Add option for request API twice, and manually or automatically compare by same API for better result.

增加一个新选项，使得能够多次请求API，并将不同的结果进行手动或同一API的自动比较，从而的到更好的结果。

**Comment by tylearymf** [comment]
现在还没有加会话机制功能，所以多次请求同一个api结果不会有啥区别，因为都是变成了单次无上下文相关的请求，但是我感觉后面加了会话机制提升也不大，可以考虑朝改进prompt方向改
