### ISSUE TITLE
Edge GPT 執行時會有錯誤，Chat GTP 回傳空的似乎沒有正常執行

### ISSUE THREAD

**Issue by SyaoranChang** [tylearymf/UniGPT#2]
你好我遇到一些錯誤，可以幫我看一下嗎?
我使用 Edge GPT 時，遇到似乎是 python 的錯誤，不知道跟 Unity 的python版本是3.10.6有沒有關係?
看到似乎有些BUG要升級到 3.11 才能解決，但Unity目前只支援到 3.10.6
如: https://github.com/acheong08/EdgeGPT/issues/234

執行的訊息:
You: Create 10 cubes
Bing: An error occurred: TypeError("Chatbot.__init__() got an unexpected keyword argument 'cookiePath'").
:::gpt.py:96

我使用 Chat GTP 時，他回傳的是空的，看 API keys 的 Last used 是顯示 Never
執行的訊息:
You: Create 10 cubes
ChatGPT:

**Comment by tylearymf** [comment]
你的new_bing_cookies.json 是不是没有创建，还是没有内容

**Comment by SyaoranChang** [comment]
我是直接Clone專案，再依教學複製Cookies 的內容過去存檔new_bing_cookies.json內了說
我剛是用 Firefox 的，我明天再試試看用 Chrome 的

**Comment by tylearymf** [comment]
更新下工程，因为EdgeGPT那边改了字段名导致的问题的

**Comment by SyaoranChang** [comment]
感謝修正~
Edge GPT 現在沒有錯誤了
然後 Chat GTP 不是很確定問題，但也可以正常運作了
